export const RESTAURANT_DETAILS_REQUEST = 'RESTAURANT_DETAILS_REQUEST'
export const RESTAURANT_DETAILS_SUCCESS = 'RESTAURANT_DETAILS_SUCCESS'
export const RESTAURANT_DETAILS_FAIL = 'RESTAURANT_DETAILS_FAIL'
export const RESTAURANT_DETAILS_RESET = 'RESTAURANT_DETAILS_RESET'

export const YELP_RESTAURANT_SAVE_REQUEST = 'YELP_RESTAURANT_SAVE_REQUEST'
export const YELP_RESTAURANT_SAVE_SUCCESS = 'YELP_RESTAURANT_SAVE_SUCCESS'
export const YELP_RESTAURANT_SAVE_FAIL = 'YELP_RESTAURANT_SAVE_FAIL'
export const YELP_RESTAURANT_SAVE_RESET = 'YELP_RESTAURANT_SAVE_RESET'